# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Project/SketchSystem_Multi1080p_HDMI/SketchSystem.srcs/sources_1/bd/system/ip/system_SketchIP_1080p_0_1/system_SketchIP_1080p_0_1.xci
# IP: The module: 'system_SketchIP_1080p_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Project/SketchSystem_Multi1080p_HDMI/SketchSystem.srcs/sources_1/bd/system/ip/system_SketchIP_1080p_0_1/sources_1/ip/outputBuffer/outputBuffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] -quiet

# IP: d:/Project/SketchSystem_Multi1080p_HDMI/SketchSystem.srcs/sources_1/bd/system/ip/system_SketchIP_1080p_0_1/sources_1/ip/div_gen_0/div_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# XDC: d:/Project/SketchSystem_Multi1080p_HDMI/SketchSystem.srcs/sources_1/bd/system/ip/system_SketchIP_1080p_0_1/sources_1/ip/outputBuffer/outputBuffer.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Project/SketchSystem_Multi1080p_HDMI/SketchSystem.srcs/sources_1/bd/system/ip/system_SketchIP_1080p_0_1/constrs_1/new/sketchConstraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_SketchIP_1080p_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Project/SketchSystem_Multi1080p_HDMI/SketchSystem.srcs/sources_1/bd/system/ip/system_SketchIP_1080p_0_1/system_SketchIP_1080p_0_1.xci
# IP: The module: 'system_SketchIP_1080p_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Project/SketchSystem_Multi1080p_HDMI/SketchSystem.srcs/sources_1/bd/system/ip/system_SketchIP_1080p_0_1/sources_1/ip/outputBuffer/outputBuffer.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] -quiet

# IP: d:/Project/SketchSystem_Multi1080p_HDMI/SketchSystem.srcs/sources_1/bd/system/ip/system_SketchIP_1080p_0_1/sources_1/ip/div_gen_0/div_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# XDC: d:/Project/SketchSystem_Multi1080p_HDMI/SketchSystem.srcs/sources_1/bd/system/ip/system_SketchIP_1080p_0_1/sources_1/ip/outputBuffer/outputBuffer.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Project/SketchSystem_Multi1080p_HDMI/SketchSystem.srcs/sources_1/bd/system/ip/system_SketchIP_1080p_0_1/constrs_1/new/sketchConstraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_SketchIP_1080p_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
